name: Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: flex420/urlaubsverwaltung

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('app/urlaubsverwaltung/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run unit tests
        run: ./app/urlaubsverwaltung/mvnw -B -DskipITs test

      - name: Verify Docker and Compose
        run: bash ./scripts/verify.sh

      - name: Extract project version
        id: version
        run: |
          VERSION=$(./app/urlaubsverwaltung/mvnw -q help:evaluate -Dexpression=project.version -DforceStdout)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "sanitized=${VERSION%-SNAPSHOT}" >> "$GITHUB_OUTPUT"
          else
            echo "sanitized=${VERSION}" >> "$GITHUB_OUTPUT"
          fi

      - name: Compute image tags
        id: tags
        run: |
          IMAGE=${{ env.IMAGE_NAME }}
          VERSION=${{ steps.version.outputs.sanitized }}
          SHORT_SHA=${GITHUB_SHA::12}
          TAGS="$IMAGE:$VERSION\n$IMAGE:sha-$SHORT_SHA"
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
              TAGS="$TAGS\n$IMAGE:latest"
            elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              REF_TAG="${GITHUB_REF#refs/tags/}"
              TAGS="$TAGS\n$IMAGE:$REF_TAG"
            fi
          fi
          printf 'list<<EOF\n%s\nEOF\n' "$TAGS" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and (optionally) push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          load: true
          tags: ${{ steps.tags.outputs.list }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.sanitized }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json